name: surgicalutopia
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  get_it: ^7.6.4
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  country_picker: ^2.0.21
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  pinput: ^3.0.1
  cached_network_image: ^3.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
