name: surgicalutopia
version: 1.0.7+7
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  get_it: ^7.6.4
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  country_picker: ^2.0.21
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  pinput: ^3.0.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.2
  firebase_storage: ^11.6.0
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  curved_navigation_bar: ^1.0.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/surgicalutopia_logo_1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
